---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: login-app
    matchExpressions:
      - {key: env, operator: In, values: [dev]}
    
  template:
    metadata:
      name: login
      labels:
        app: login-app
        env: dev
    spec:
      containers:
      - name: login-app
        image: docker.io/dpthub/dpt6http:1.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
