# Deploy nodePort Services
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx-service

spec:
  selector:
    app: nginx
    env: dev

  type: LoadBalancer
  ports:
  - port: 80
    nodePort: 31001
    targetPort: 80