# Deploy ReplicaSet Controller
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: login-app
    matchExpressions:
      - {key: env, operator: In, values: [dev]}
    
  template:
    metadata:
      name: login
      labels:
        app: login-app
        env: dev
    spec:
      containers:
      - name: login-app
        image: docker.io/dpthub/dpt6http:1.0
